showpath

diff --git a/Utilities/SetupLinuxBox/BashrcEasyExtras b/Utilities/SetupLinuxBox/BashrcEasyExtras
--- a/Utilities/SetupLinuxBox/BashrcEasyExtras
+++ b/Utilities/SetupLinuxBox/BashrcEasyExtras
@@ -1,16 +1,36 @@
 
+#==================#
+#=== Elven Code ===#
+#==================#
+
 if [ -z "$SSH_AUTH_SOCK" ] ; then
     eval `ssh-agent`
 fi
 
+set-node-path () {
+    if ! echo "$NODE_PATH" | /bin/grep -Eq "(^|:)$1($|:)" ; then
+        NODE_PATH="$1:$NODE_PATH"
+    fi
+}
+
+set-system-path () {
+    if ! echo "$PATH" | /bin/grep -Eq "(^|:)$1($|:)" ; then
+        PATH="$1:$PATH"
+    fi
+}
+
+# Node Support
+set-node-path "$HOME/npm/lib/node_modules"
+set-system-path "$HOME/npm/bin"
+
 # Edit and uncomment to load a key automatically.
-#ssh-add -l | grep -q "made on rohan-elf"  
-#if [ $? -eq 0 ]; then  
-#    echo OK  
-#else  
-#    echo FAIL  
-#    ssh-add ~/.ssh/id_rsa  
+#ssh-add -l | grep -q "made on rohan-elf"
+#if [ $? -eq 0 ]; then
+#    echo OK
+#else
+#    echo FAIL
+#    ssh-add ~/.ssh/id_rsa
 #fi
 
-export NODE_PATH="$HOME/npm/lib/node_modules"
-export PATH="$PATH:$HOME/npm/bin"
+# === End Elven Code === #
+
