extras

diff --git a/Utilities/SetupLinuxBox/BashrcEasyExtras b/Utilities/SetupLinuxBox/BashrcEasyExtras
--- a/Utilities/SetupLinuxBox/BashrcEasyExtras
+++ b/Utilities/SetupLinuxBox/BashrcEasyExtras
@@ -3,5 +3,13 @@ if [ -z "$SSH_AUTH_SOCK" ] ; then
     eval `ssh-agent`
 fi
 
+#ssh-add -l | grep -q "made on rohan-elf"  
+#if [ $? -eq 0 ]; then  
+#    echo OK  
+#else  
+#    echo FAIL  
+#    ssh-add ~/.ssh/id_rsa  
+#fi
+
 export NODE_PATH="$HOME/npm/lib/node_modules"
 export PATH="$PATH:$HOME/npm/bin"
diff --git a/Utilities/SetupLinuxBox/BashrcExtras b/Utilities/SetupLinuxBox/BashrcExtras
--- a/Utilities/SetupLinuxBox/BashrcExtras
+++ b/Utilities/SetupLinuxBox/BashrcExtras
@@ -2,6 +2,15 @@ if [ -z "$SSH_AUTH_SOCK" ] ; then
     eval `ssh-agent` 
 fi
 
+# Edit and uncomment to load a key automatically.
+#ssh-add -l | grep -q "made on rohan-elf"  
+#if [ $? -eq 0 ]; then  
+#    echo OK  
+#else  
+#    echo FAIL  
+#    ssh-add ~/.ssh/id_rsa  
+#fi
+
 export CHROME_BIN=/usr/bin/chromium-browser
 
 export NODE_PATH=:$HOME/npm/lib/node_modules
